title: Tongkai Wu's Homepage
page-top-title: Tongkai Wu
top-section-bg-text: Computer and Information Engineering 
home-subtitle: Tongkai Wu&ensp;|&ensp;吴同凯
copyright-text: '&copy; Tongkai Wu 2023-2026. All Rights Reserved.'
